model: SASRecAttr
n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.2
attn_dropout_prob: 0.2
hidden_act: gelu
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: CE
gpu_id: 0
use_gpu: true
seed: 404
state: DEBUG
reproducibility: true
data_path: /ssd/dataset/
show_progress: true
save_dataset: false
save_dataloaders: false
log_wandb: true
load_col:
  inter:
  - session_id_hash
  - server_timestamp_epoch_ms
  - product_sku_hash
  - first_result_product
  - item_id_type
  item:
  - first_result_product
  - item_id_type
seq_separator: /
MAX_ITEM_LIST_LENGTH: 30
USER_ID_FIELD: session_id_hash
TIME_FIELD: server_timestamp_epoch_ms
val_interval: null
filter_inter_by_user_or_item: false
user_inter_num_interval: '[5,inf)'
item_inter_num_interval: '[5,inf)'
epochs: 50
train_batch_size: 64
train_neg_sample_args: null
learner: adam
learning_rate: 0.001
eval_step: 5
stopping_step: 10
clip_grad_norm: null
weight_decay: 0.001
benchmark_filename:
- train
- validation
- test
eval_args:
  group_by: user
  item_id: item_id_type
  mode:
    test: full
    valid: full
  order: TO
  split:
    RS:
    - 0.8
    - 0.1
    - 0.1
repeatable: true
metrics:
- Recall
- NDCG
- MRR
topk:
- 1
- 5
- 10
- 20
valid_metric: Recall@10
valid_metric_bigger: true
eval_batch_size: 64
valid_batch_size: 64
loss_decimal_place: 4
metric_decimal_place: 4
checkpoint_dir: /home/ls6/fischer/plp-paper/recbole/coveo-sl-search/firstitem_id/varfix/404/
ITEM_ID_FIELD: first_result_product
wandb_name: coveo-sl-search-firstitem_id-sasrec
wandb_project: plp-coveo-search
