model: CaserAttr
embedding_size: 64
dropout_prob: 0.4
reg_weight: 1e-4
L: 5
nv: 4
nh: 8
loss_type: CE
gpu_id: 0
use_gpu: true
seed: 6
state: DEBUG
reproducibility: true
data_path: /ssd/dataset/
show_progress: true
save_dataset: false
save_dataloaders: false
log_wandb: true
load_col:
  inter: [session_id_hash, server_timestamp_epoch_ms, category_product_id, item_id_type] 
  item: [category_product_id, item_id_type]
MAX_ITEM_LIST_LENGTH: 30
USER_ID_FIELD: session_id_hash
TIME_FIELD: server_timestamp_epoch_ms
val_interval: null
filter_inter_by_user_or_item: false
user_inter_num_interval: '[5,inf)'
item_inter_num_interval: '[5,inf)'
epochs: 50
train_batch_size: 64
train_neg_sample_args: null
learner: adam
learning_rate: 0.001
eval_step: 5
stopping_step: 10
clip_grad_norm: null
weight_decay: 0.001
benchmark_filename:
- train
- validation
- test
eval_args:
  group_by: user
  item_id: item_id_type
  mode:
    test: full
    valid: full
  order: TO
  split:
    RS:
    - 0.8
    - 0.1
    - 0.1
repeatable: true
metrics:
- Recall
- NDCG
- MRR
topk:
- 1
- 5
- 10
- 20
valid_metric: Recall@10
valid_metric_bigger: true
eval_batch_size: 64
valid_batch_size: 64
loss_decimal_place: 4
metric_decimal_place: 4
checkpoint_dir: /home/ls6/fischer/plp-paper/recbole/coveo-pageview/title_id/varfix/6/
ITEM_ID_FIELD: category_product_id
wandb_name: coveo-pageview-title_id-caser
wandb_project: plp-coveo-pageview
