model: BERT4RecTesting
n_layers: 2                     # (int) The number of transformer layers in transformer encoder.
n_heads: 2                      # (int) The number of attention heads for multi-head attention layer.
hidden_size: 64                 # (int) The number of features in the hidden state.
inner_size: 256                  # (int) The inner hidden size in feed-forward layer.
hidden_dropout_prob: 0.2        # (float) The probability of an element to be zeroed.
attn_dropout_prob: 0.2          # (float) The probability of an attention score to be zeroed.
hidden_act: 'gelu'              # (str) The activation function in feed-forward layer.
layer_norm_eps: 1e-12           # (float) A value added to the denominator for numerical stability.
initializer_range: 0.02         # (float) The standard deviation for normal initialization.
mask_ratio: 0.2              # (float) The probability for a item replaced by MASK token.
loss_type: 'CE'                 # (str) The type of loss function.
transform: mask_itemseqAndAttributes
finetune: BATCH # NONE, BATCH, SAMPLE, ALWAYS
masking_options: ONLY_MASK # RANDOM_VALUE
num_of_masked_items_choice: variable #max or actual or variable
min_masked_sample_bugfix: 1  #minimum number of masked items
ft_ratio: 0.1    # (str) The type of loss function. Range in ['BPR', 'CE'].

gpu_id: 0
use_gpu: true
seed: 212
state: DEBUG
reproducibility: true
data_path: /ssd/dataset/
show_progress: true
save_dataset: false
save_dataloaders: false
log_wandb: true
load_col:
  inter:
  - userId
  - timestamp
  - title
  - genres
  - title_genres
  - item_id_type
  item:
  - title
  - item_id_type
seq_separator: '|'
seq_len:
  genres: 6
MAX_ITEM_LIST_LENGTH: 200
USER_ID_FIELD: userId
RATING_FIELD: rating
TIME_FIELD: timestamp
val_interval: null
filter_inter_by_user_or_item: false
user_inter_num_interval: '[5,inf)'
item_inter_num_interval: '[5,inf)'
epochs: 100
train_batch_size: 64
train_neg_sample_args: null
learner: adam
learning_rate: 0.001
eval_step: 5
stopping_step: 10
clip_grad_norm: null
weight_decay: 0.001
benchmark_filename:
- train
- validation
- test
eval_args:
  item_id: item_id_type
  group_by: user
  order: TO
  mode: full
repeatable: true
metrics:
- Recall
- NDCG
- MRR
topk:
- 1
- 5
- 10
- 20
valid_metric: Recall@10
valid_metric_bigger: true
eval_batch_size: 64
valid_batch_size: 64
loss_decimal_place: 4
metric_decimal_place: 4
checkpoint_dir: /home/ls6/fischer/plp-paper/recbole/ml-20m-extended/bert4rec/title_id/
ITEM_ID_FIELD: title
wandb_name: ml-20m-extended-title_id-bert4rec
wandb_project: plp-ml-20m
