items:
  attribute_fusion: 'sum'
  attributes_listpage_only: True
  item_id_type_settings:
    name: "item_id_type"
    extra_embbedding: false
  attributes:
    genres:
      embedding_type: 'multihot'
      len: 6

# general
gpu_id: 0
use_gpu: True
seed: 212
state: DEBUG  #INFO
reproducibility: True
data_path: '/ssd/dataset/'
show_progress: True
save_dataset: False
save_dataloaders: False
log_wandb: True

# dataset
load_col:
  inter: [userId, timestamp, title, genres, item_id_type]
  item: [title, item_id_type]
#train_subsequences: True
seq_separator: "|"
seq_len:
  genres: 6
MAX_ITEM_LIST_LENGTH: 200
USER_ID_FIELD: userId
RATING_FIELD: rating
TIME_FIELD: timestamp

# Filtering
val_interval: ~
filter_inter_by_user_or_item: False
user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

# training settings
epochs: 100
train_batch_size: 64
train_neg_sample_args: null
learner: adam
learning_rate: 0.001
eval_step: 5
stopping_step: 10
clip_grad_norm: ~
weight_decay: 0.001

# evaluation settings
benchmark_filename: ["train","validation","test"]
eval_args:
  item_id: item_id_type
  group_by: user
  order: TO
  mode: full

repeatable: True
metrics: ["Recall","NDCG","MRR"]
topk: [1,5,10,20]
valid_metric: Recall@10
valid_metric_bigger: True
eval_batch_size: 64
valid_batch_size: 64
loss_decimal_place: 4
metric_decimal_place: 4